[package]

name          = "mio"
version       = "0.3.1"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://carllerche.github.io/mio/mio"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
log   = "0.3.1"
#nix   = "0.3.2"
time  = "0.1.23"
#bytes = "0.2.4"

[dependencies.nix]
git = "https://github.com/fhartwig/nix-rust.git"
branch = "rustup"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dev-dependencies]
env_logger = "0.3.0"
tempdir    = "0.3.3"

[[test]]

name = "test"
path = "test/test.rs"
